const catalogInfo = `[
    {"image": "image/catalog/men_1.png",
    "alt": "men_1",
    "name": "ELLERY X M'O CAPSULE",
    "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
    "price": "$52.00"},
    {"image": "image/catalog/women_2.png",
    "alt": "women_2",
    "name": "ELLERY X M'O CAPSULE",
    "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
    "price": "$52.00"},
    {"image": "image/catalog/men_3.png",
    "alt": "men_3",
    "name": "ELLERY X M'O CAPSULE",
    "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
    "price": "$52.00"},
    {"image": "image/catalog/men_4.png",
    "alt": "men_4",
    "name": "ELLERY X M'O CAPSULE",
    "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
    "price": "$52.00"},
    {"image": "image/catalog/women_5.png",
    "alt": "women_5",
    "name": "ELLERY X M'O CAPSULE",
    "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
    "price": "$52.00"},
    {"image": "image/catalog/women_6.png",
    "alt": "women_6",
    "name": "ELLERY X M'O CAPSULE",
    "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
    "price": "$52.00"}
]`